version: "3.9"

services:
  scrapper:
    build: .
    container_name: Scrapper
    command: bash -c "python src"
    volumes:
      - ./input:/usr/app/input
      - ./output:/usr/app/output
      - ./src:/usr/app/src
    environment:
      - INPUT_PATH=/usr/app/input/job.json
      - LOG_LEVEL=INFO
      - LOG_PATH=/usr/app/output/
      - LOG_FILE_NAME=crawler.log